source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.2'
use_frameworks!

target :'PhotoMap' do
    pod 'AWSS3', '~> 2.6.1'    # For file transfers
    pod 'AWSCognito', '~> 2.6.1'    #For data sync
    pod 'AWSAuthCore', '~> 2.6.1'
end

